### ISSUE TITLE
haskus-utils does not build with haskus-utils-variant-3.0

### ISSUE THREAD

**Issue by poscat0x04** [haskus/packages#31]
```
haskus-utils        > /tmp/stack-329766d28a844ae1/haskus-utils-1.4/src/lib/Haskus/Utils/Flow.hs:45:1: error:
haskus-utils        >     Could not find module ‘Haskus.Utils.Variant.Flow’
```

**Comment by poscat0x04** [comment]
nvm. I messed up my config

**Comment by poscat0x04** [comment]
Oh the package on hackage needs updating

**Comment by hsyl20** [comment]
Fixed in `haskus-utils-1.5`
